### PR TITLE
Make it installable via pip

### PR DESCRIPTION
**Pull request by muelli**
This PR makes it work with current Wx as well as installs executables. Now you should be able to pip install the package. Even straight from git, i.e. pip install 'git+https://github.com/Conservatory/openstv.git#egg=openstv'

### CODE REVIEW

**Comment by kfogel** [comment]
Hi, @muelli.  I'm conflicted: on the one hand, the Conservatory is not trying to be the official upstream for any of these projects; on the other hand, what if there is no other place to be the upstream?

So let me ask: are you actively maintaining a fork of OpenSTV right now?  Should Conservatory treat you as upstream?

**Comment by muelli** [comment]
hrm.
I wouldn't call it "actively maintaining". We use OpenSTV within GNOME. And I thought I'd share how I think OpenSTV could be improved.
That said, I'm happy to host OpenSTV under my namespace, merge patches, and make a release every so often.  I'm not planning to actively develop it, though.

**Comment by kfogel** [comment]
That sounds like the closest thing it has to maintainership.  I'd say go for it!  We'll treat you as the upstream for the time being; if for some reason you ever have to drop it (which would be perfectly understandable and should be the cause of no guilt whatsoever), then the Conservatory can once again become the static home until such time as someone else comes along.

**Comment by muelli** [comment]
Okay. Then please follow me to https://github.com/muelli/openstv

**Pull request closed without merging**
